---
title: "Fluctuating experiment"
output: html_document
---
```{r, include=FALSE}

# Library
library(dygraphs)
library(xts)          # To make the convertion data-frame / xts format
library(tidyverse)
library(lubridate)
library(htmlwidgets)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(scales) 
library(gridExtra)
```

```{r, echo=FALSE}
spicata200<-read.delim("~/desktop/ECOLAB!/FLUCTUATING EXPERIMENT/data/spicata_28Junio_15d.txt",header = TRUE, sep = ",")
spicata200$Hora.de.Chile<-format(as.POSIXct(spicata200$Hora.de.Chile), format = "%y-%m-%d %H:%M")
spicata200$Hora.de.Chile<-as_datetime(spicata200$Hora.de.Chile, format = "%y-%m-%d %H:%M")
spicata200$date<-date(spicata200$Hora.de.Chile)
spicata200<-spicata200[60:1510,]
spicata600<-read.delim("~/desktop/ECOLAB!/FLUCTUATING EXPERIMENT/data/spicata_600_15d_26ago.txt",header = TRUE, sep = ",")
spicata600$Hora.de.Chile<-format(as.POSIXct(spicata600$Hora.de.Chile), format = "%y-%m-%d %H:%M")
spicata600$Hora.de.Chile<-as_datetime(spicata600$Hora.de.Chile, format = "%y-%m-%d %H:%M")
spicata600$date<-date(spicata600$Hora.de.Chile)
spicata600<-spicata600[60:1338,]
spicata1000<-read.delim("~/desktop/ECOLAB!/FLUCTUATING EXPERIMENT/data/spicata_1000_15d_26ago.txt",header = TRUE, sep = ",")
spicata1000$Hora.de.Chile<-format(as.POSIXct(spicata1000$Hora.de.Chile), format = "%y-%m-%d %H:%M")
spicata1000$Hora.de.Chile<-as_datetime(spicata1000$Hora.de.Chile, format = "%y-%m-%d %H:%M")
spicata1000$date<-date(spicata1000$Hora.de.Chile)
spicata1000<-spicata1000[60:1337,]
full<-rbind(spicata200,spicata600,spicata1000)
full$biomass<-as.factor(c(rep(200,1451),rep(600,1279),rep(1000,1278)))
full$time<-(c(seq(0,21750,by=15),seq(0,19170,by=15),seq(0,19155,by=15)))/1440
```

```{r, echo=FALSE}
# Then you can create the xts necessary to use dygraph
don <- xts(x = spicata600$Dissolved.Oxygen, order.by = spicata600$Hora.de.Chile)

# Finally the plot
p<-dygraph(don) %>%
  dyOptions(labelsUTC = FALSE, fillGraph=FALSE, fillAlpha=0.1, drawGrid = FALSE, colors="#D8AE5A") %>%
  dyRangeSelector() %>%
  dyCrosshair(direction = "vertical") %>%
  dyHighlight(highlightCircleSize = 5, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = FALSE)  %>%
  dyRoller(rollPeriod = 1)

# save the widget
saveWidget(p, file=paste0( getwd(), "/images/dygraphs1.html"))
p

# Then you can create the xts necessary to use dygraph
don2 <- xts(x = spicata200$Dissolved.Oxygen, order.by = spicata200$Hora.de.Chile)

# Finally the plot
p2<-dygraph(don2) %>%
  dyOptions(labelsUTC = FALSE, fillGraph=FALSE, fillAlpha=0.1, drawGrid = FALSE, colors="#D8AE5A") %>%
  dyRangeSelector() %>%
  dyCrosshair(direction = "vertical") %>%
  dyHighlight(highlightCircleSize = 5, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = FALSE)  %>%
  dyRoller(rollPeriod = 1)

# save the widget
saveWidget(p2, file=paste0( getwd(), "/images/dygraphs2.html"))
p2

# Then you can create the xts necessary to use dygraph
don3 <- xts(x = spicata1000$Dissolved.Oxygen, order.by = spicata1000$Hora.de.Chile)

# Finally the plot
p3<-dygraph(don3) %>%
  dyOptions(labelsUTC = FALSE, fillGraph=FALSE, fillAlpha=0.1, drawGrid = FALSE, colors="#D8AE5A") %>%
  dyRangeSelector() %>%
  dyCrosshair(direction = "vertical") %>%
  dyHighlight(highlightCircleSize = 5, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = FALSE)  %>%
  dyRoller(rollPeriod = 1)

# save the widget
saveWidget(p3, file=paste0( getwd(), "/images/dygraphs3.html"))
p3
```

